-- AI 모델용 관광지 데이터 테이블
-- PostgreSQL 대응
--   DATETIME      -> TIMESTAMP
--   AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY

CREATE TABLE spot_cache (
    content_id VARCHAR(40) PRIMARY KEY,
    spot_name   VARCHAR(100) NOT NULL,
    area_cd     VARCHAR(10)  NOT NULL,
    signgu_cd   VARCHAR(10)  NOT NULL,
    lcls_nm     VARCHAR(50),
    mcls_nm     VARCHAR(50),
    map_x       DOUBLE PRECISION,
    map_y       DOUBLE PRECISION,
    hub_rank    INT,
    vector      JSON NOT NULL,
    keywords    JSON,
    updated_at  TIMESTAMP
);

CREATE TABLE spot_relation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_nm     VARCHAR(100) NOT NULL,
    related_cd  VARCHAR(40),
    related_nm  VARCHAR(100),
    related_mcls VARCHAR(50),
    rlte_rank   INT
);

CREATE TABLE spot_congestion (
    content_id    VARCHAR(40) NOT NULL,
    forecast_date DATE        NOT NULL,
    congestion    FLOAT,
    PRIMARY KEY (content_id, forecast_date),
    CONSTRAINT fk_spot_congestion_spot_cache
        FOREIGN KEY (content_id) REFERENCES spot_cache (content_id)
);

CREATE TABLE user_survey (
    user_id       VARCHAR(40) PRIMARY KEY,
    last_survey   JSON,
    last_travel_at TIMESTAMP
);

-- 조회에 자주 사용될 가능성이 높은 컬럼 인덱스
CREATE INDEX idx_spot_cache_area_signgu
    ON spot_cache (area_cd, signgu_cd);

CREATE INDEX idx_spot_relation_spot_nm
    ON spot_relation (spot_nm);

CREATE INDEX idx_spot_congestion_forecast_date
    ON spot_congestion (forecast_date);
