ALTER TABLE app_user
    ADD COLUMN mascot VARCHAR(50) NOT NULL DEFAULT 'trophy',
    ADD COLUMN theme_color VARCHAR(7) NOT NULL DEFAULT '#5B44E8';

CREATE TABLE app_user_survey (
    user_id BIGINT PRIMARY KEY REFERENCES app_user (id) ON DELETE CASCADE,
    survey_json TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    stadium VARCHAR(200),
    course_type VARCHAR(100),
    course_json TEXT NOT NULL,
    saved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_saved_course_user_saved_at ON saved_course (user_id, saved_at DESC);

CREATE TABLE trip_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    stadium VARCHAR(200) NOT NULL,
    match_name VARCHAR(200),
    trip_date DATE,
    course_title VARCHAR(200),
    rating INT,
    visited_spot_ids TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_trip_rating CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5))
);

CREATE INDEX idx_trip_history_user_created_at ON trip_history (user_id, created_at DESC);

CREATE TABLE recommendation_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    survey_json TEXT NOT NULL,
    result_json TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recommendation_request_user_created_at
    ON recommendation_request (user_id, created_at DESC);
